### ISSUE TITLE
Initializing data: too many open files

### ISSUE THREAD

**Issue by hugo** [steveklabnik/warehouse#10]
```
Charon:warehouse hugo$ RUST_LOG=warehouse=info multirust run nightly cargo run
     Running `target/debug/warehouse`
INFO:warehouse: Starting server
INFO:warehouse: Initializing data...
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 24, message: "Too many open files" } }', ../src/libcore/result.rs:734
An unknown error occurred
```

OS X (10.11) has a default `ulimit -n` of 256, which causes this issue. Upping the file descriptor limit works fine so not sure if you want to consider this a bug or not, but thought it was worth reporting.

**Comment by steveklabnik** [comment]
Ahhh interesting. Right.

Startup and initial load is _really_ slow, due to opening a few thousand files. So I'm going to consider this a bug :)

**Comment by steveklabnik** [comment]
This is https://github.com/rust-lang/rust/issues/27707

**Comment by hugo** [comment]
rust-lang/rust/issues/27707 was closed, closing this also
