### ISSUE TITLE
make the has_many work

### ISSUE THREAD

**Issue by steveklabnik** [steveklabnik/warehouse#2]
https://github.com/steveklabnik/warehouse/blob/master/frontend/app/models/crate.js#L4

I think this is because either
1. I'm not generating the correct JSON for the included data
2. I need to implement the sub-routes anyway

**Comment by fsmanuel** [comment]
I was going to open a PR but found your solution much better.
I guess https://github.com/steveklabnik/warehouse/blob/master/src/totally_not_a_database.rs#L45 has to be resolved to show more than the last version.

**Comment by steveklabnik** [comment]
Fixed! https://github.com/steveklabnik/warehouse/pull/6
